# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
php:
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 7.1

script:
  - ./composer install
  - vendor/bin/phpunit